"""Pull Spinfinite/Improvado daily betting CPA reports from the
newsweek@agentmail.to inbox.

Improvado's AI Agent emails the report daily (subject:
"Newsweek - Daily report", sender: agent@improvado.io). Body is
plain-text, tab-separated. No CSV attachment.

Report body shape:
    Report Summary
    Affiliate: Company 18 (Newsweek) | Report Date: YYYY-MM-DD

    Metric  Total
    Total Clicks   <n>
    Registrations  <n>
    FTPs  <n>
    Net Cash  $<x.xx>
    Full Breakdown
    Click Date  Sub ID 1  [Sub ID 2]  Total Clicks  Registrations  FTPs  Net Cash
    YYYY-MM-DD  <subid1>  [<subid2>]  <n>  <n>  <n>  $<x.xx>
    ...
    Generated by Improvado AI Agent

The Sub ID 2 column is optional — present once the advertiser starts
populating it. Parser handles both shapes.

agentmail.to API (no SDK — plain urllib HTTP), same auth pattern as
dv_attention_client.py.
"""
from __future__ import annotations

import io
import json
import logging
import re
import urllib.error
import urllib.parse
import urllib.request
from datetime import date as _date

import pandas as pd

logger = logging.getLogger(__name__)

AGENTMAIL_BASE = "https://api.agentmail.to/v0"
# Forwarded reports arrive as "Fwd: Newsweek - Daily report" — use substring
# match so both direct and forwarded subjects pass.
IMPROVADO_SUBJECT_NEEDLE = "Newsweek - Daily report"
# Provenance marker that has to appear in the body. Forwarded emails strip
# the original sender, so we verify by looking for the Improvado footer.
IMPROVADO_BODY_MARKER = "Generated by Improvado AI Agent"


def _api_get(path: str, *, api_key: str, raw: bool = False):
    url = f"{AGENTMAIL_BASE}{path}"
    req = urllib.request.Request(
        url,
        headers={
            "Authorization": f"Bearer {api_key}",
            "Accept": "application/json" if not raw else "*/*",
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            content = r.read()
            return content if raw else json.loads(content)
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(
            f"agentmail.to GET {url} failed: HTTP {e.code} {e.reason} :: {body[:500]}"
        ) from e


def list_improvado_messages(api_key: str, inbox_id: str, limit: int = 30) -> list[dict]:
    """List recent messages whose subject contains the Improvado report title.
    Sender is not checked — reports are typically forwarded, which strips the
    original sender. Body-level provenance is verified at parse time via the
    Improvado footer marker.
    """
    raw = _api_get(f"/inboxes/{inbox_id}/messages?limit={limit}", api_key=api_key)
    messages = raw.get("messages", raw.get("data", [])) if isinstance(raw, dict) else (raw or [])
    matches = []
    for m in messages:
        subj = (m.get("subject") or "").strip()
        if IMPROVADO_SUBJECT_NEEDLE in subj:
            matches.append(m)
    logger.info(
        "agentmail: scanned %d recent message(s); %d match Improvado betting",
        len(messages), len(matches),
    )
    return matches


def get_message_detail(api_key: str, inbox_id: str, message_id: str) -> dict:
    return _api_get(f"/inboxes/{inbox_id}/messages/{message_id}", api_key=api_key)


# ---- Parser ----

_HEADER_RE = re.compile(r"^\s*Click Date\s+Sub ID 1(\s+Sub ID 2)?\s+Total Clicks\s+Registrations\s+FTPs\s+Net Cash\s*$")
_REPORT_DATE_RE = re.compile(r"Report Date:\s*(\d{4}-\d{2}-\d{2})", re.I)
_MONEY_RE = re.compile(r"^\$?\s*(-?[\d,]+(?:\.\d+)?)$")

def _money(s: str) -> float:
    """'$20.00' -> 20.0, '$0.00' -> 0.0, '-$5' -> -5.0."""
    s = s.strip()
    if not s: return 0.0
    m = _MONEY_RE.match(s.replace(",", ""))
    return float(m.group(1)) if m else 0.0

def _int(s: str) -> int:
    s = s.strip().replace(",", "")
    return int(s) if s and s.lstrip("-").isdigit() else 0


def parse_improvado_body(body: str) -> tuple[pd.DataFrame, dict]:
    """Parse the text body of an Improvado report email.

    Returns (rows_df, summary_dict).
      rows_df columns: date, sub_id_1, sub_id_2 (str | None), clicks, registrations, ftps, net_cash
      summary_dict:    report_date, totals (clicks/regs/ftps/net_cash), provenance_ok
    """
    lines = body.splitlines()
    summary = {"report_date": None, "totals": {}}
    # Provenance check: forwarded emails may not have a trustworthy sender,
    # so confirm the body contains the Improvado footer.
    summary["provenance_ok"] = IMPROVADO_BODY_MARKER in body

    # 1) Report date (header section)
    for ln in lines[:20]:
        m = _REPORT_DATE_RE.search(ln)
        if m:
            summary["report_date"] = m.group(1)
            break

    # 2) Find the Full Breakdown header row
    header_idx = None
    has_subid2 = False
    for i, ln in enumerate(lines):
        m = _HEADER_RE.match(ln)
        if m:
            header_idx = i
            has_subid2 = bool(m.group(1))
            break

    # 3) Parse data rows below the header until a blank line or "Generated by"
    rows = []
    if header_idx is not None:
        for ln in lines[header_idx + 1:]:
            if not ln.strip(): continue
            if ln.lower().startswith("generated by"): break
            # Prefer SINGLE-tab split (preserves empty fields). If the row has
            # no tabs (multi-space formatting), fall back to runs of 2+ spaces.
            if "\t" in ln:
                parts = ln.rstrip("\n").split("\t")
            else:
                parts = re.split(r"\s{2,}", ln.strip())
            if has_subid2:
                if len(parts) >= 7:
                    date_s, s1, s2, clk, reg, ftp, cash = parts[:7]
                elif len(parts) == 6:
                    # sub_id_2 column present in header but this row's value is blank
                    date_s, s1, clk, reg, ftp, cash = parts
                    s2 = None
                else:
                    continue
            else:
                if len(parts) >= 6:
                    date_s, s1, clk, reg, ftp, cash = parts[:6]
                    s2 = None
                else:
                    continue
            rows.append({
                "date":          date_s.strip(),
                "sub_id_1":      s1.strip(),
                "sub_id_2":      (s2.strip() if s2 else None),
                "clicks":        _int(clk),
                "registrations": _int(reg),
                "ftps":          _int(ftp),
                "net_cash":      _money(cash),
            })

    # 4) Pull totals from the Report Summary block
    for ln in lines[:30]:
        s = ln.strip()
        if s.startswith("Total Clicks"):
            summary["totals"]["clicks"] = _int(s.split(None, 2)[-1] if "\t" not in s else s.split("\t")[-1])
        elif s.startswith("Registrations"):
            summary["totals"]["registrations"] = _int(s.split(None, 1)[-1] if "\t" not in s else s.split("\t")[-1])
        elif s.startswith("FTPs"):
            summary["totals"]["ftps"] = _int(s.split(None, 1)[-1] if "\t" not in s else s.split("\t")[-1])
        elif s.startswith("Net Cash"):
            summary["totals"]["net_cash"] = _money(s.split(None, 2)[-1] if "\t" not in s else s.split("\t")[-1])

    df = pd.DataFrame(rows)
    if not df.empty:
        df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.date
        df = df.dropna(subset=["date"])
    return df, summary


def pull_improvado(api_key: str, inbox_id: str) -> tuple[pd.DataFrame, dict]:
    """End-to-end: poll inbox, take newest provenance-verified message, parse body.

    Walks newest-to-oldest matching messages; the first one whose body contains
    the Improvado footer wins. This skips spoofs / replies / hand-written
    drafts that happen to share the subject.
    """
    messages = list_improvado_messages(api_key, inbox_id, limit=30)
    if not messages:
        return pd.DataFrame(), {}
    messages.sort(key=lambda m: m.get("sent_at") or m.get("created_at") or "", reverse=True)
    for m in messages:
        detail = get_message_detail(api_key, inbox_id, m["id"])
        body = detail.get("text") or detail.get("body") or detail.get("html") or ""
        if IMPROVADO_BODY_MARKER not in body:
            logger.info("Skipping message %s — no Improvado footer (likely a reply/forward thread)", m["id"])
            continue
        df, summary = parse_improvado_body(body)
        summary["message_id"] = m["id"]
        summary["received_at"] = m.get("sent_at") or m.get("created_at")
        summary["subject"] = m.get("subject")
        return df, summary
    return pd.DataFrame(), {}
